# -*- coding: utf-8 -*-
"""hw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SA9gIcJQx_rSxLoD1KXHwBg0n3Eivv3N
"""

#reads creates a dataframe from a URL that points to a CSV file
def readfile(url):
    import pandas as pd
    return pd.read_csv(url)

#test
readfile('https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv')

def test_create_dataframe(df,colname):
    if list(df.columns).sort ==colname.sort and df.shape[0]>10 and len(df.dtypes.unique())==1:
      return True
    else:
      return False

#test
import pandas as pd
df1= pd.DataFrame({'float': [1.0]})
df1.columns
df1.dtypes
len(df1.dtypes.unique())

test_create_dataframe(df1,['float'])

